# Generated by Django 5.2.4 on 2025-07-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid"),
                    ("shipped", "Shipped"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending_approval",
                max_length=20,
            ),
        ),
    ]
